server:
  port: 8080  # Port of the client application

spring:
  application:
    name: user-service  # Logical name of the service (appears in Eureka)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka Server
  instance:
    prefer-ip-address: true  # Use IP instead of hostname for registration
